// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.blazerobotics.orion.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.blazerobotics.orion.Robot;

/**
 *
 */
public class  AutonomousCommand extends CommandGroup {

    public AutonomousCommand() {
    	addSequential(new CanArmTimedCommand(2.6, 0.3, false));
    	addSequential(new WaitCommand(1));
    	addSequential(new DriveToPointCommand(100_000 * -1.4, 0.5, 1.5)); //feet ish
    	//addSequential(new WaitCommand(1));
    	addSequential(new CanArmTimedCommand(0.8, -1, true));
    	//addSequential(new WaitCommand(1));
    	addParallel(new CanArmTimedCommand(10, -1, false));
    	addSequential(new DriveToPointCommand(100_000 * 13, 0.7, 0));
    	
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return super.isFinished();
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
